spring:
  datasource:
    password: 2303
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger
server:
  port: 7777
